export const mockJobs = [
  {
    id: 1,
    title: "Software / Web Developer Intern",
    company: "Smart Finance",
    location: "Anna Nagar, Chennai",
    salary: "₹12,000 - ₹25,000 monthly",
    type: "Full Time",
    experience: "Any experience",
    skills: "HTML, CSS, JavaScript, React",
    workMode: "Work from Office",
    isUrgent: true,
    isNew: true,
    postedDate: "2023-05-15",
  },
  {
    id: 2,
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "Bangalore, Karnataka",
    salary: "₹20,000 - ₹35,000 monthly",
    type: "Part Time",
    experience: "1-2 years",
    skills: "React, JavaScript, CSS",
    workMode: "Remote",
    isUrgent: false,
    isNew: false,
    postedDate: "2023-05-10",
  },
  {
    id: 3,
    title: "Backend Engineer",
    company: "Data Systems Ltd",
    location: "Hyderabad, Telangana",
    salary: "₹25,000 - ₹40,000 monthly",
    type: "Full Time",
    experience: "2-3 years",
    skills: "Node.js, MongoDB, Express",
    workMode: "Hybrid",
    isUrgent: true,
    isNew: false,
    postedDate: "2023-05-14",
  },
  {
    id: 4,
    title: "Software / Web Developer Intern",
    company: "Smart Finance",
    location: "Anna Nagar, Chennai",
    salary: "₹12,000 - ₹25,000 monthly",
    type: "Full Time",
    experience: "Any experience",
    skills: "HTML, CSS, JavaScript, React",
    workMode: "Work from Office",
    isUrgent: true,
    isNew: true,
    postedDate: "2023-05-15",
  },
  {
    id: 5,
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "Bangalore, Karnataka",
    salary: "₹20,000 - ₹35,000 monthly",
    type: "Part Time",
    experience: "1-2 years",
    skills: "React, JavaScript, CSS",
    workMode: "Remote",
    isUrgent: false,
    isNew: false,
    postedDate: "2023-05-10",
  },
  {
    id: 6,
    title: "Backend Engineer",
    company: "Data Systems Ltd",
    location: "Hyderabad, Telangana",
    salary: "₹25,000 - ₹40,000 monthly",
    type: "Full Time",
    experience: "2-3 years",
    skills: "Node.js, MongoDB, Express",
    workMode: "Hybrid",
    isUrgent: true,
    isNew: false,
    postedDate: "2023-05-14",
  },
  {
    id: 7,
    title: "Software / Web Developer Intern",
    company: "Smart Finance",
    location: "Anna Nagar, Chennai",
    salary: "₹12,000 - ₹25,000 monthly",
    type: "Full Time",
    experience: "Any experience",
    skills: "HTML, CSS, JavaScript, React",
    workMode: "Work from Office",
    isUrgent: true,
    isNew: true,
    postedDate: "2023-05-15",
  },
  {
    id: 8,
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "Bangalore, Karnataka",
    salary: "₹20,000 - ₹35,000 monthly",
    type: "Part Time",
    experience: "1-2 years",
    skills: "React, JavaScript, CSS",
    workMode: "Remote",
    isUrgent: false,
    isNew: false,
    postedDate: "2023-05-10",
  },
  {
    id: 9,
    title: "Backend Engineer",
    company: "Data Systems Ltd",
    location: "Hyderabad, Telangana",
    salary: "₹25,000 - ₹40,000 monthly",
    type: "Full Time",
    experience: "2-3 years",
    skills: "Node.js, MongoDB, Express",
    workMode: "Hybrid",
    isUrgent: true,
    isNew: false,
    postedDate: "2023-05-14",
  },
  {
    id: 10,
    title: "Software / Web Developer Intern",
    company: "Smart Finance",
    location: "Anna Nagar, Chennai",
    salary: "₹12,000 - ₹25,000 monthly",
    type: "Full Time",
    experience: "Any experience",
    skills: "HTML, CSS, JavaScript, React",
    workMode: "Work from Office",
    isUrgent: true,
    isNew: true,
    postedDate: "2023-05-15",
  },
  {
    id: 11,
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "Bangalore, Karnataka",
    salary: "₹20,000 - ₹35,000 monthly",
    type: "Part Time",
    experience: "1-2 years",
    skills: "React, JavaScript, CSS",
    workMode: "Remote",
    isUrgent: false,
    isNew: false,
    postedDate: "2023-05-10",
  },
  {
    id: 12,
    title: "Backend Engineer",
    company: "Data Systems Ltd",
    location: "Hyderabad, Telangana",
    salary: "₹25,000 - ₹40,000 monthly",
    type: "Full Time",
    experience: "2-3 years",
    skills: "Node.js, MongoDB, Express",
    workMode: "Hybrid",
    isUrgent: true,
    isNew: false,
    postedDate: "2023-05-14",
  },
  {
    id: 13,
    title: "Software / Web Developer Intern",
    company: "Smart Finance",
    location: "Anna Nagar, Chennai",
    salary: "₹12,000 - ₹25,000 monthly",
    type: "Full Time",
    experience: "Any experience",
    skills: "HTML, CSS, JavaScript, React",
    workMode: "Work from Office",
    isUrgent: true,
    isNew: true,
    postedDate: "2023-05-15",
  },
  {
    id: 14,
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "Bangalore, Karnataka",
    salary: "₹20,000 - ₹35,000 monthly",
    type: "Part Time",
    experience: "1-2 years",
    skills: "React, JavaScript, CSS",
    workMode: "Remote",
    isUrgent: false,
    isNew: false,
    postedDate: "2023-05-10",
  },
  {
    id: 15,
    title: "Backend Engineer",
    company: "Data Systems Ltd",
    location: "Hyderabad, Telangana",
    salary: "₹25,000 - ₹40,000 monthly",
    type: "Full Time",
    experience: "2-3 years",
    skills: "Node.js, MongoDB, Express",
    workMode: "Hybrid",
    isUrgent: true,
    isNew: false,
    postedDate: "2023-05-14",
  },
  {
    id: 16,
    title: "Software / Web Developer Intern",
    company: "Smart Finance",
    location: "Anna Nagar, Chennai",
    salary: "₹12,000 - ₹25,000 monthly",
    type: "Full Time",
    experience: "Any experience",
    skills: "HTML, CSS, JavaScript, React",
    workMode: "Work from Office",
    isUrgent: true,
    isNew: true,
    postedDate: "2023-05-15",
  },
  {
    id: 17,
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "Bangalore, Karnataka",
    salary: "₹20,000 - ₹35,000 monthly",
    type: "Part Time",
    experience: "1-2 years",
    skills: "React, JavaScript, CSS",
    workMode: "Remote",
    isUrgent: false,
    isNew: false,
    postedDate: "2023-05-10",
  },
  {
    id: 18,
    title: "Backend Engineer",
    company: "Data Systems Ltd",
    location: "Hyderabad, Telangana",
    salary: "₹25,000 - ₹40,000 monthly",
    type: "Full Time",
    experience: "2-3 years",
    skills: "Node.js, MongoDB, Express",
    workMode: "Hybrid",
    isUrgent: true,
    isNew: false,
    postedDate: "2023-05-14",
  },
  {
    id: 19,
    title: "Software / Web Developer Intern",
    company: "Smart Finance",
    location: "Anna Nagar, Chennai",
    salary: "₹12,000 - ₹25,000 monthly",
    type: "Full Time",
    experience: "Any experience",
    skills: "HTML, CSS, JavaScript, React",
    workMode: "Work from Office",
    isUrgent: true,
    isNew: true,
    postedDate: "2023-05-15",
  },
  {
    id: 20,
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "Bangalore, Karnataka",
    salary: "₹20,000 - ₹35,000 monthly",
    type: "Part Time",
    experience: "1-2 years",
    skills: "React, JavaScript, CSS",
    workMode: "Remote",
    isUrgent: false,
    isNew: false,
    postedDate: "2023-05-10",
  },
  {
    id: 21,
    title: "Backend Engineer",
    company: "Data Systems Ltd",
    location: "Hyderabad, Telangana",
    salary: "₹25,000 - ₹40,000 monthly",
    type: "Full Time",
    experience: "2-3 years",
    skills: "Node.js, MongoDB, Express",
    workMode: "Hybrid",
    isUrgent: true,
    isNew: false,
    postedDate: "2023-05-14",
  },
  {
    id: 22,
    title: "Software / Web Developer Intern",
    company: "Smart Finance",
    location: "Anna Nagar, Chennai",
    salary: "₹12,000 - ₹25,000 monthly",
    type: "Full Time",
    experience: "Any experience",
    skills: "HTML, CSS, JavaScript, React",
    workMode: "Work from Office",
    isUrgent: true,
    isNew: true,
    postedDate: "2023-05-15",
  },
  {
    id: 23,
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "Bangalore, Karnataka",
    salary: "₹20,000 - ₹35,000 monthly",
    type: "Part Time",
    experience: "1-2 years",
    skills: "React, JavaScript, CSS",
    workMode: "Remote",
    isUrgent: false,
    isNew: false,
    postedDate: "2023-05-10",
  },
  {
    id: 24,
    title: "Backend Engineer",
    company: "Data Systems Ltd",
    location: "Hyderabad, Telangana",
    salary: "₹25,000 - ₹40,000 monthly",
    type: "Full Time",
    experience: "2-3 years",
    skills: "Node.js, MongoDB, Express",
    workMode: "Hybrid",
    isUrgent: true,
    isNew: false,
    postedDate: "2023-05-14",
  },
  {
    id: 25,
    title: "Software / Web Developer Intern",
    company: "Smart Finance",
    location: "Anna Nagar, Chennai",
    salary: "₹12,000 - ₹25,000 monthly",
    type: "Full Time",
    experience: "Any experience",
    skills: "HTML, CSS, JavaScript, React",
    workMode: "Work from Office",
    isUrgent: true,
    isNew: true,
    postedDate: "2023-05-15",
  },
  {
    id: 26,
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "Bangalore, Karnataka",
    salary: "₹20,000 - ₹35,000 monthly",
    type: "Part Time",
    experience: "1-2 years",
    skills: "React, JavaScript, CSS",
    workMode: "Remote",
    isUrgent: false,
    isNew: false,
    postedDate: "2023-05-10",
  },
  {
    id: 27,
    title: "Backend Engineer",
    company: "Data Systems Ltd",
    location: "Hyderabad, Telangana",
    salary: "₹25,000 - ₹40,000 monthly",
    type: "Full Time",
    experience: "2-3 years",
    skills: "Node.js, MongoDB, Express",
    workMode: "Hybrid",
    isUrgent: true,
    isNew: false,
    postedDate: "2023-05-14",
  },
  {
    id: 28,
    title: "Software / Web Developer Intern",
    company: "Smart Finance",
    location: "Anna Nagar, Chennai",
    salary: "₹12,000 - ₹25,000 monthly",
    type: "Full Time",
    experience: "Any experience",
    skills: "HTML, CSS, JavaScript, React",
    workMode: "Work from Office",
    isUrgent: true,
    isNew: true,
    postedDate: "2023-05-15",
  },
  {
    id: 29,
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "Bangalore, Karnataka",
    salary: "₹20,000 - ₹35,000 monthly",
    type: "Part Time",
    experience: "1-2 years",
    skills: "React, JavaScript, CSS",
    workMode: "Remote",
    isUrgent: false,
    isNew: false,
    postedDate: "2023-05-10",
  },
  {
    id: 30,
    title: "Backend Engineer",
    company: "Data Systems Ltd",
    location: "Hyderabad, Telangana",
    salary: "₹25,000 - ₹40,000 monthly",
    type: "Full Time",
    experience: "2-3 years",
    skills: "Node.js, MongoDB, Express",
    workMode: "Hybrid",
    isUrgent: true,
    isNew: false,
    postedDate: "2023-05-14",
  },
  {
    id: 31,
    title: "Software / Web Developer Intern",
    company: "Smart Finance",
    location: "Anna Nagar, Chennai",
    salary: "₹12,000 - ₹25,000 monthly",
    type: "Full Time",
    experience: "Any experience",
    skills: "HTML, CSS, JavaScript, React",
    workMode: "Work from Office",
    isUrgent: true,
    isNew: true,
    postedDate: "2023-05-15",
  },
  {
    id: 32,
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "Bangalore, Karnataka",
    salary: "₹20,000 - ₹35,000 monthly",
    type: "Part Time",
    experience: "1-2 years",
    skills: "React, JavaScript, CSS",
    workMode: "Remote",
    isUrgent: false,
    isNew: false,
    postedDate: "2023-05-10",
  },
  {
    id: 33,
    title: "Backend Engineer",
    company: "Data Systems Ltd",
    location: "Hyderabad, Telangana",
    salary: "₹25,000 - ₹40,000 monthly",
    type: "Full Time",
    experience: "2-3 years",
    skills: "Node.js, MongoDB, Express",
    workMode: "Hybrid",
    isUrgent: true,
    isNew: false,
    postedDate: "2023-05-14",
  },
  {
    id: 34,
    title: "Software / Web Developer Intern",
    company: "Smart Finance",
    location: "Anna Nagar, Chennai",
    salary: "₹12,000 - ₹25,000 monthly",
    type: "Full Time",
    experience: "Any experience",
    skills: "HTML, CSS, JavaScript, React",
    workMode: "Work from Office",
    isUrgent: true,
    isNew: true,
    postedDate: "2023-05-15",
  },
  {
    id: 35,
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "Bangalore, Karnataka",
    salary: "₹20,000 - ₹35,000 monthly",
    type: "Part Time",
    experience: "1-2 years",
    skills: "React, JavaScript, CSS",
    workMode: "Remote",
    isUrgent: false,
    isNew: false,
    postedDate: "2023-05-10",
  },
  {
    id: 36,
    title: "Backend Engineer",
    company: "Data Systems Ltd",
    location: "Hyderabad, Telangana",
    salary: "₹25,000 - ₹40,000 monthly",
    type: "Full Time",
    experience: "2-3 years",
    skills: "Node.js, MongoDB, Express",
    workMode: "Hybrid",
    isUrgent: true,
    isNew: false,
    postedDate: "2023-05-14",
  },
  {
    id: 37,
    title: "Software / Web Developer Intern",
    company: "Smart Finance",
    location: "Anna Nagar, Chennai",
    salary: "₹12,000 - ₹25,000 monthly",
    type: "Full Time",
    experience: "Any experience",
    skills: "HTML, CSS, JavaScript, React",
    workMode: "Work from Office",
    isUrgent: true,
    isNew: true,
    postedDate: "2023-05-15",
  },
  {
    id: 38,
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "Bangalore, Karnataka",
    salary: "₹20,000 - ₹35,000 monthly",
    type: "Part Time",
    experience: "1-2 years",
    skills: "React, JavaScript, CSS",
    workMode: "Remote",
    isUrgent: false,
    isNew: false,
    postedDate: "2023-05-10",
  },
  {
    id: 39,
    title: "Backend Engineer",
    company: "Data Systems Ltd",
    location: "Hyderabad, Telangana",
    salary: "₹25,000 - ₹40,000 monthly",
    type: "Full Time",
    experience: "2-3 years",
    skills: "Node.js, MongoDB, Express",
    workMode: "Hybrid",
    isUrgent: true,
    isNew: false,
    postedDate: "2023-05-14",
  },
  {
    id: 40,
    title: "Software / Web Developer Intern",
    company: "Smart Finance",
    location: "Anna Nagar, Chennai",
    salary: "₹12,000 - ₹25,000 monthly",
    type: "Full Time",
    experience: "Any experience",
    skills: "HTML, CSS, JavaScript, React",
    workMode: "Work from Office",
    isUrgent: true,
    isNew: true,
    postedDate: "2023-05-15",
  },
  {
    id: 41,
    title: "Frontend Developer",
    company: "Tech Solutions Inc.",
    location: "Bangalore, Karnataka",
    salary: "₹20,000 - ₹35,000 monthly",
    type: "Part Time",
    experience: "1-2 years",
    skills: "React, JavaScript, CSS",
    workMode: "Remote",
    isUrgent: false,
    isNew: false,
    postedDate: "2023-05-10",
  },
  {
    id: 42,
    title: "Backend Engineer",
    company: "Data Systems Ltd",
    location: "Hyderabad, Telangana",
    salary: "₹25,000 - ₹40,000 monthly",
    type: "Full Time",
    experience: "2-3 years",
    skills: "Node.js, MongoDB, Express",
    workMode: "Hybrid",
    isUrgent: true,
    isNew: false,
    postedDate: "2023-05-14",
  },
];
